#ifndef CG_LSP_GO_LSP_H
#define CG_LSP_GO_LSP_H

#include "type_rep.h"
#include "scope.h"
#include "type_registry.h"
#include "../cg.h"

// GoLSPContext holds state for Go expression type evaluation within a file.
typedef struct {
    CGArena* arena;
    const char* source;
    int source_len;
    const CGTypeRegistry* registry;
    CGScope* current_scope;

    // Import map: local_name -> package QN (arena-allocated)
    const char** import_local_names;   // NULL-terminated
    const char** import_package_qns;   // NULL-terminated
    int import_count;

    // Current function context
    const char* enclosing_func_qn;
    const char* package_qn;  // module QN for this file

    // Output: resolved calls accumulate here
    CGResolvedCallArray* resolved_calls;

    // Debug mode (CG_LSP_DEBUG env)
    bool debug;
} GoLSPContext;

// Initialize a GoLSPContext for processing one file.
void go_lsp_init(GoLSPContext* ctx, CGArena* arena, const char* source, int source_len,
    const CGTypeRegistry* registry, const char* package_qn, CGResolvedCallArray* out);

// Add an import mapping.
void go_lsp_add_import(GoLSPContext* ctx, const char* local_name, const char* package_qn);

// Process all functions in a file's AST, evaluating types and resolving calls.
// root is the tree-sitter root node of the file.
void go_lsp_process_file(GoLSPContext* ctx, TSNode root);

// Evaluate the type of a Go expression node.
const CGType* go_eval_expr_type(GoLSPContext* ctx, TSNode node);

// Parse a Go type AST node into a CGType.
const CGType* go_parse_type_node(GoLSPContext* ctx, TSNode node);

// Process a Go statement, binding variables into the current scope.
void go_process_statement(GoLSPContext* ctx, TSNode node);

// Evaluate a builtin call (make, new, append, len, cap, delete).
const CGType* go_eval_builtin_call(GoLSPContext* ctx, const char* name, TSNode args);

// Look up a field or method on a type, traversing embedded types.
const CGRegisteredFunc* go_lookup_field_or_method(GoLSPContext* ctx,
    const char* type_qn, const char* member_name);

// Entry point: build registry from file's own defs + run LSP resolution.
// Called from cg_extract_file() after definitions and imports are extracted.
void cg_run_go_lsp(CGArena* arena, CGFileResult* result,
    const char* source, int source_len, TSNode root);

// Register Go stdlib types and functions into a registry.
// Auto-generated by scripts/gen-go-stdlib.go.
void cg_go_stdlib_register(CGTypeRegistry* reg, CGArena* arena);

// --- Cross-file LSP resolution ---

// Simplified definition for cross-file type/function registration.
// String fields are borrowed (caller owns memory until cg_run_go_lsp_cross returns).
typedef struct {
    const char* qualified_name;
    const char* short_name;
    const char* label;          // "Function", "Method", "Type", "Interface"
    const char* receiver_type;  // for methods: receiver type QN (NULL for functions)
    const char* def_module_qn;  // module QN where this def lives (for type text qualification)
    const char* return_types;   // "|"-separated return type texts, e.g. "*File|error"
    const char* embedded_types; // "|"-separated embedded type QNs (for struct embedding)
    const char* field_defs;     // "|"-separated "name:type" pairs (for struct fields, e.g. "Binder:Binder|Name:string")
    const char* method_names_str; // "|"-separated method names for interfaces (e.g. "Get|Put|Delete")
    bool is_interface;
    CGLanguage lang;           // language of the file that defined this — used by Tier 2 per-language registry build to filter all_defs
} CGLSPDef;

// Parse source, build registry from defs + stdlib, run LSP.
// Re-parses source with tree-sitter internally.
// defs includes both file-local and cross-file definitions.
// import_names/import_qns are parallel arrays of length import_count.
// Results written to out (arena-allocated).
void cg_run_go_lsp_cross(
    CGArena* arena,
    const char* source, int source_len,
    const char* module_qn,
    CGLSPDef* defs, int def_count,
    const char** import_names, const char** import_qns, int import_count,
    TSTree* cached_tree,           // NULL = parse internally
    CGResolvedCallArray* out);

/* Tier 2 (gopls package-summary pattern):
 * Build a project-wide, finalized CGTypeRegistry from all Go defs ONCE.
 * Run cross-file LSP per file using that shared registry — no per-file
 * registry build, O(1) lookups, no Phase 1b/1c mutations. Reg is borrowed
 * from arena (arena owns the storage); reg pointer is valid for arena
 * lifetime. */
CGTypeRegistry* cg_go_build_cross_registry(
    CGArena* arena, CGLSPDef* defs, int def_count);

void cg_run_go_lsp_cross_with_registry(
    CGArena* arena,
    const char* source, int source_len,
    const char* module_qn,
    CGTypeRegistry* reg,          // pre-built, finalized, READ-ONLY
    const char** import_names, const char** import_qns, int import_count,
    TSTree* cached_tree,           // NULL = parse internally
    CGResolvedCallArray* out);

/* Tier 3: AST-walk-free fast resolver. Iterates result->calls and
 * resolves fully-qualified calls (pkg.Func) directly from the
 * pre-built registry — no tree-sitter parse, no AST walk. Returns
 * the count of calls that STILL need the slow path (methods on
 * locals + qualified calls we couldn't resolve). When the return
 * value is 0, the caller can skip the cg_run_go_lsp_cross_with_
 * registry parse+walk entirely. Resolved entries are appended to
 * result->resolved_calls in result->arena. */
int cg_go_fast_resolve_qualified_calls(
    CGFileResult* result,
    CGTypeRegistry* reg,
    const char** import_names, const char** import_qns, int import_count);

// --- Batch cross-file LSP ---

// Per-file input for batch Go LSP processing.
typedef struct {
    const char* source;
    int source_len;
    const char* module_qn;
    TSTree* cached_tree;           // from TSTree caching (NULL = parse internally)
    CGLSPDef* defs;               // combined file-local + cross-file defs
    int def_count;
    const char** import_names;     // parallel arrays, import_count long
    const char** import_qns;
    int import_count;
} CGBatchGoLSPFile;

// Process multiple Go files' cross-file LSP in one CGo call.
// out must point to file_count pre-zeroed CGResolvedCallArray structs.
// Uses per-file arenas internally; results are copied to the output arena.
void cg_batch_go_lsp_cross(
    CGArena* arena,
    CGBatchGoLSPFile* files, int file_count,
    CGResolvedCallArray* out);

#endif // CG_LSP_GO_LSP_H
