#ifndef CG_LSP_PY_LSP_H
#define CG_LSP_PY_LSP_H

#include "type_rep.h"
#include "scope.h"
#include "type_registry.h"
#include "../cg.h"
#include "go_lsp.h" // CGLSPDef, CGResolvedCallArray reused across languages

// Lambda body record. When a lambda is assigned to a name (`fn =
// lambda x: x.method()`), we stash its parameter list + body so the
// next call site (`fn(arg)`) can do call-site driven inference.
typedef struct {
    const char *name;   // bound name, e.g. "fn"
    TSNode lambda_node; // the lambda AST node
} CGLambdaEntry;

// Function-as-dict-value entry. When `funcs = {"a": foo, "b": bar}` is
// seen, we record the per-key target QN so `funcs["a"]()` emits an
// edge to foo.
typedef struct {
    const char *var_name;    // e.g. "funcs"
    const char *literal_key; // e.g. "a"
    const char *target_qn;   // e.g. "test.main.foo"
} CGDictLiteralEntry;

// PyLSPContext holds state for one Python file's type evaluation.
typedef struct {
    CGArena *arena;
    const char *source;
    int source_len;
    const CGTypeRegistry *registry;
    CGScope *current_scope;

    // Import map: local_name -> module_qn (arena-allocated, NULL-terminated).
    // Built from CGFileResult.imports.
    const char **import_local_names;
    const char **import_module_qns;
    int import_count;

    // Current function/class context for resolving `self`/`cls` and emitting
    // caller QNs.
    const char *enclosing_func_qn;
    const char *enclosing_class_qn;
    const char *module_qn;

    // Output: resolved calls accumulate here.
    CGResolvedCallArray *resolved_calls;

    // Syntactic-call list (result->calls), borrowed from the per-file
    // extraction result. The downstream pipeline only turns a resolved_call
    // into a CALLS edge when a *syntactic* CGCall with the same
    // (enclosing_func_qn, callee short-name) exists here. Operator/subscript
    // dunder desugaring (`s[k]` -> T.__getitem__, `a + b` -> T.__add__) never
    // appears in result->calls because a `subscript`/`binary_operator` is not
    // a `call` node, so the syntactic extractor produced no call. When this is
    // non-NULL, py_emit_dunder_call injects a matching synthetic CGCall so the
    // recovered dunder call becomes a real CALLS edge. NULL in the cross-file
    // path (no result->calls available there). Mirrors RustLSPContext.syn_calls.
    CGCallArray *syn_calls;

    // Lambda registry: simple linear list, looked up by name.
    CGLambdaEntry *lambdas;
    int lambda_count;
    int lambda_cap;

    // Dict-literal-as-dispatch-table tracking.
    CGDictLiteralEntry *dict_literals;
    int dict_literal_count;
    int dict_literal_cap;

    // Debug mode (CG_LSP_DEBUG env, shared across all language LSPs).
    bool debug;
} PyLSPContext;

// Initialize a PyLSPContext for processing one file.
void py_lsp_init(PyLSPContext *ctx, CGArena *arena, const char *source, int source_len,
                 const CGTypeRegistry *registry, const char *module_qn, CGResolvedCallArray *out);

// Add an import mapping (call once per CGImport entry).
void py_lsp_add_import(PyLSPContext *ctx, const char *local_name, const char *module_qn);

// Bind every recorded import into the root scope. Idempotent. Called from
// py_lsp_process_file before AST traversal. Exposed for unit tests that
// don't need a tree-sitter parse.
void py_lsp_bind_imports(PyLSPContext *ctx);

// Test hook: lookup a name in the context's scope chain. Returns
// cg_type_unknown() if not bound.
const CGType *py_lsp_lookup_in_scope(const PyLSPContext *ctx, const char *name);

// Process all functions/classes in a file's AST, evaluating types and resolving calls.
// root must be the tree-sitter Python `module` node.
void py_lsp_process_file(PyLSPContext *ctx, TSNode root);

// Entry point: build registry from file's own defs + run LSP resolution.
// Mirrors cg_run_go_lsp / cg_run_c_lsp.
void cg_run_py_lsp(CGArena *arena, CGFileResult *result, const char *source, int source_len,
                    TSNode root);

// Register Python stdlib types and functions into a registry.
// Auto-generated by scripts/gen-py-stdlib.py from typeshed.
// Phase 10 fills the body; Phase 2 ships a no-op so linkage works.
void cg_python_stdlib_register(CGTypeRegistry *reg, CGArena *arena);

// --- Cross-file LSP resolution ---

void cg_run_py_lsp_cross(CGArena *arena, const char *source, int source_len,
                          const char *module_qn, CGLSPDef *defs, int def_count,
                          const char **import_names, const char **import_qns, int import_count,
                          TSTree *cached_tree, // NULL = parse internally
                          CGResolvedCallArray *out);

/* Tier 2: pre-built per-language registry (mirrors Go pilot).
 * Filters all_defs to Python entries, builds + finalizes once. */
CGTypeRegistry *cg_py_build_cross_registry(CGArena *arena, CGLSPDef *defs, int def_count);

void cg_run_py_lsp_cross_with_registry(CGArena *arena, const char *source, int source_len,
                                        const char *module_qn,
                                        CGTypeRegistry *reg, // pre-built, finalized, READ-ONLY
                                        const char **import_names, const char **import_qns,
                                        int import_count, TSTree *cached_tree,
                                        CGResolvedCallArray *out);

// --- Batch cross-file LSP ---

typedef struct {
    const char *source;
    int source_len;
    const char *module_qn;
    TSTree *cached_tree; // from TSTree caching (NULL = parse internally)
    CGLSPDef *defs;     // combined file-local + cross-file defs
    int def_count;
    const char **import_names; // parallel arrays, import_count long
    const char **import_qns;
    int import_count;
} CGBatchPyLSPFile;

void cg_batch_py_lsp_cross(CGArena *arena, CGBatchPyLSPFile *files, int file_count,
                            CGResolvedCallArray *out);

#endif // CG_LSP_PY_LSP_H
