"""ReAct streaming callback protocol."""
from __future__ import annotations

from typing import Protocol
class StreamCallback(Protocol):
    async def on_llm_token(self, token: str) -> None: ...
    async def on_tool_call(self, tool_name: str, args: dict) -> None: ...
    async def on_tool_result(self, tool_name: str, result: str, failed: bool = False) -> None: ...
    async def on_error(self, error: str) -> None: ...
    async def on_complete(self, output: str) -> None: ...
