name: oncall-agent-ui

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kyc-agent-ui
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - oncall-agent

networks:
  oncall-agent:
    external: true
    name: oncall-agent
