-- migrations/015_project_intelligence.sql
-- Project Intelligence layer for the Code Crawler.
-- Run after 014_gateway_assignments.sql.
--
-- Stores the layered, LLM-generated understanding of a repository produced by
-- the index flow's intelligence nodes (SummarizeModules, BuildProjectBrief,
-- ExtractStandards). Each row is one document:
--
--   doc_type = 'brief'     doc_path = ''     → product/domain/architecture narrative
--   doc_type = 'domain'    doc_path = ''     → business entity glossary
--   doc_type = 'features'  doc_path = ''     → feature → code mapping
--   doc_type = 'standards' doc_path = ''     → coding-conventions profile
--   doc_type = 'module'    doc_path = <dir>  → per-directory "wiki" doc (many rows)
--
-- ``files_sha256`` records the aggregate fingerprint of the files the doc was
-- generated from, so module docs can be refreshed incrementally (a module whose
-- fingerprint is unchanged is skipped on reindex). Rows are scoped by repo_name
-- and removed by CrawlerService.delete_index alongside the kg_* tables.

CREATE TABLE IF NOT EXISTS repo_docs (
    repo_name    VARCHAR(255) NOT NULL,
    doc_type     VARCHAR(32)  NOT NULL,   -- brief | domain | features | standards | module
    doc_path     VARCHAR(512) NOT NULL DEFAULT '',  -- '' for repo-level docs; directory for modules
    content      JSONB        NOT NULL,
    files_sha256 VARCHAR(64),
    model_id     VARCHAR(255),
    tokens_in    INTEGER      NOT NULL DEFAULT 0,
    tokens_out   INTEGER      NOT NULL DEFAULT 0,
    generated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (repo_name, doc_type, doc_path)
);

COMMENT ON TABLE repo_docs IS
'Project-intelligence documents (brief, domain model, feature map, coding standards, per-module wiki) generated by the crawler index flow.';

CREATE INDEX IF NOT EXISTS repo_docs_repo_type_idx
ON repo_docs (repo_name, doc_type);
